apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: pv-jdownloader-media-smb
spec:
  capacity:
    storage: 1Gi # Makes no difference
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: jdownloader-media
    volumeAttributes:
      source: "//fileserver.lan.santos.party/media"
    nodeStageSecretRef:
      name: fileserver-smb-creds
      namespace: csi-driver-smb
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-jdownloader-media-smb
  namespace: jdownloader
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-jdownloader-media-smb
  storageClassName: smb
