apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wg-easy
  namespace: wg-easy
spec:
  storageClassName: 'longhorn'
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
