apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 12h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '58.x'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1m
  values:
    grafana:
      persistence:
        enabled: true
        type: pvc
    prometheus:
      prometheusSpec:
        retention: 1y
        retentionSize: "9GiB"
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              resources:
                requests:
                  storage: 10Gi

