apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: internet-monitor
spec:
  interval: 12h
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: '8.12.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 12h
  values:
    serviceMonitor:
      enabled: true
      defaults:
        labels:
          release: prometheus
      targets:
        - name: google.com
          url: https://google.com

