apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: internet-monitor
  namespace: internet-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: internet-monitor
  podMetricsEndpoints:
    - port: speedtest
      interval: "10m"
      scrapeTimeout: "2m"
